// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int number = Integer.parseInt(args[0]);
		int times = 0;
		double lower = 0;
		double upper = 0;
		while (number > times)
		{
			double rand = Math.random();
			if (rand > 0.5)
				upper++;
			else
				lower++;
			times++;
		}
		double ratio = upper / lower;
		System.out.println(upper + " " + lower + " Ratio: " + ratio);
	}
}
